// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: sync/lease.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLeaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip  string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	App string `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Ttl int32  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *CreateLeaseRequest) Reset() {
	*x = CreateLeaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lease_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseRequest) ProtoMessage() {}

func (x *CreateLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lease_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseRequest.ProtoReflect.Descriptor instead.
func (*CreateLeaseRequest) Descriptor() ([]byte, []int) {
	return file_sync_lease_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLeaseRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CreateLeaseRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CreateLeaseRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type CreateLeaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseId string `protobuf:"bytes,1,opt,name=leaseId,proto3" json:"leaseId,omitempty"`
}

func (x *CreateLeaseResponse) Reset() {
	*x = CreateLeaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lease_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseResponse) ProtoMessage() {}

func (x *CreateLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lease_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseResponse.ProtoReflect.Descriptor instead.
func (*CreateLeaseResponse) Descriptor() ([]byte, []int) {
	return file_sync_lease_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLeaseResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type KeepLeaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseId string `protobuf:"bytes,1,opt,name=leaseId,proto3" json:"leaseId,omitempty"`
	Ttl     int32  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *KeepLeaseRequest) Reset() {
	*x = KeepLeaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lease_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepLeaseRequest) ProtoMessage() {}

func (x *KeepLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lease_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepLeaseRequest.ProtoReflect.Descriptor instead.
func (*KeepLeaseRequest) Descriptor() ([]byte, []int) {
	return file_sync_lease_proto_rawDescGZIP(), []int{2}
}

func (x *KeepLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *KeepLeaseRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type KeepLeaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeepLeaseResponse) Reset() {
	*x = KeepLeaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lease_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepLeaseResponse) ProtoMessage() {}

func (x *KeepLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lease_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepLeaseResponse.ProtoReflect.Descriptor instead.
func (*KeepLeaseResponse) Descriptor() ([]byte, []int) {
	return file_sync_lease_proto_rawDescGZIP(), []int{3}
}

type DropLeaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseId string `protobuf:"bytes,1,opt,name=leaseId,proto3" json:"leaseId,omitempty"`
}

func (x *DropLeaseRequest) Reset() {
	*x = DropLeaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lease_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropLeaseRequest) ProtoMessage() {}

func (x *DropLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lease_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropLeaseRequest.ProtoReflect.Descriptor instead.
func (*DropLeaseRequest) Descriptor() ([]byte, []int) {
	return file_sync_lease_proto_rawDescGZIP(), []int{4}
}

func (x *DropLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type DropLeaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropLeaseResponse) Reset() {
	*x = DropLeaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lease_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropLeaseResponse) ProtoMessage() {}

func (x *DropLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lease_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropLeaseResponse.ProtoReflect.Descriptor instead.
func (*DropLeaseResponse) Descriptor() ([]byte, []int) {
	return file_sync_lease_proto_rawDescGZIP(), []int{5}
}

var File_sync_lease_proto protoreflect.FileDescriptor

var file_sync_lease_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x22, 0x48, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74,
	0x74, 0x6c, 0x22, 0x2f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x10, 0x4b, 0x65, 0x65, 0x70, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x74, 0x74, 0x6c, 0x22, 0x13, 0x0a, 0x11, 0x4b, 0x65, 0x65, 0x70, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x44, 0x72, 0x6f, 0x70,
	0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x72, 0x6f, 0x70, 0x4c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sync_lease_proto_rawDescOnce sync.Once
	file_sync_lease_proto_rawDescData = file_sync_lease_proto_rawDesc
)

func file_sync_lease_proto_rawDescGZIP() []byte {
	file_sync_lease_proto_rawDescOnce.Do(func() {
		file_sync_lease_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_lease_proto_rawDescData)
	})
	return file_sync_lease_proto_rawDescData
}

var file_sync_lease_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sync_lease_proto_goTypes = []interface{}{
	(*CreateLeaseRequest)(nil),  // 0: sync.CreateLeaseRequest
	(*CreateLeaseResponse)(nil), // 1: sync.CreateLeaseResponse
	(*KeepLeaseRequest)(nil),    // 2: sync.KeepLeaseRequest
	(*KeepLeaseResponse)(nil),   // 3: sync.KeepLeaseResponse
	(*DropLeaseRequest)(nil),    // 4: sync.DropLeaseRequest
	(*DropLeaseResponse)(nil),   // 5: sync.DropLeaseResponse
}
var file_sync_lease_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_lease_proto_init() }
func file_sync_lease_proto_init() {
	if File_sync_lease_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sync_lease_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLeaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lease_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLeaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lease_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepLeaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lease_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepLeaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lease_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropLeaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lease_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropLeaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_lease_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_lease_proto_goTypes,
		DependencyIndexes: file_sync_lease_proto_depIdxs,
		MessageInfos:      file_sync_lease_proto_msgTypes,
	}.Build()
	File_sync_lease_proto = out.File
	file_sync_lease_proto_rawDesc = nil
	file_sync_lease_proto_goTypes = nil
	file_sync_lease_proto_depIdxs = nil
}
