// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: sync/lock.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseId       string `protobuf:"bytes,1,opt,name=leaseId,proto3" json:"leaseId,omitempty"`
	TenantId      string `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	GlobalConcern string `protobuf:"bytes,3,opt,name=globalConcern,proto3" json:"globalConcern,omitempty"`
	LocalConcern  string `protobuf:"bytes,4,opt,name=localConcern,proto3" json:"localConcern,omitempty"`
}

func (x *LocalLockRequest) Reset() {
	*x = LocalLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLockRequest) ProtoMessage() {}

func (x *LocalLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLockRequest.ProtoReflect.Descriptor instead.
func (*LocalLockRequest) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{0}
}

func (x *LocalLockRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LocalLockRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LocalLockRequest) GetGlobalConcern() string {
	if x != nil {
		return x.GlobalConcern
	}
	return ""
}

func (x *LocalLockRequest) GetLocalConcern() string {
	if x != nil {
		return x.LocalConcern
	}
	return ""
}

type LocalLockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LocalLockResponse) Reset() {
	*x = LocalLockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLockResponse) ProtoMessage() {}

func (x *LocalLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLockResponse.ProtoReflect.Descriptor instead.
func (*LocalLockResponse) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{1}
}

type LocalUnlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseId       string `protobuf:"bytes,1,opt,name=leaseId,proto3" json:"leaseId,omitempty"`
	TenantId      string `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	GlobalConcern string `protobuf:"bytes,3,opt,name=globalConcern,proto3" json:"globalConcern,omitempty"`
	LocalConcern  string `protobuf:"bytes,4,opt,name=localConcern,proto3" json:"localConcern,omitempty"`
}

func (x *LocalUnlockRequest) Reset() {
	*x = LocalUnlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalUnlockRequest) ProtoMessage() {}

func (x *LocalUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalUnlockRequest.ProtoReflect.Descriptor instead.
func (*LocalUnlockRequest) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{2}
}

func (x *LocalUnlockRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LocalUnlockRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LocalUnlockRequest) GetGlobalConcern() string {
	if x != nil {
		return x.GlobalConcern
	}
	return ""
}

func (x *LocalUnlockRequest) GetLocalConcern() string {
	if x != nil {
		return x.LocalConcern
	}
	return ""
}

type LocalUnlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LocalUnlockResponse) Reset() {
	*x = LocalUnlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalUnlockResponse) ProtoMessage() {}

func (x *LocalUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalUnlockResponse.ProtoReflect.Descriptor instead.
func (*LocalUnlockResponse) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{3}
}

type GlobalLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseId       string `protobuf:"bytes,1,opt,name=leaseId,proto3" json:"leaseId,omitempty"`
	TenantId      string `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	GlobalConcern string `protobuf:"bytes,3,opt,name=globalConcern,proto3" json:"globalConcern,omitempty"`
}

func (x *GlobalLockRequest) Reset() {
	*x = GlobalLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLockRequest) ProtoMessage() {}

func (x *GlobalLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLockRequest.ProtoReflect.Descriptor instead.
func (*GlobalLockRequest) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalLockRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *GlobalLockRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GlobalLockRequest) GetGlobalConcern() string {
	if x != nil {
		return x.GlobalConcern
	}
	return ""
}

type GlobalLockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GlobalLockResponse) Reset() {
	*x = GlobalLockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLockResponse) ProtoMessage() {}

func (x *GlobalLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLockResponse.ProtoReflect.Descriptor instead.
func (*GlobalLockResponse) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{5}
}

type GlobalUnlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseId       string `protobuf:"bytes,1,opt,name=leaseId,proto3" json:"leaseId,omitempty"`
	TenantId      string `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	GlobalConcern string `protobuf:"bytes,3,opt,name=globalConcern,proto3" json:"globalConcern,omitempty"`
}

func (x *GlobalUnlockRequest) Reset() {
	*x = GlobalUnlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalUnlockRequest) ProtoMessage() {}

func (x *GlobalUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalUnlockRequest.ProtoReflect.Descriptor instead.
func (*GlobalUnlockRequest) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{6}
}

func (x *GlobalUnlockRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *GlobalUnlockRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GlobalUnlockRequest) GetGlobalConcern() string {
	if x != nil {
		return x.GlobalConcern
	}
	return ""
}

type GlobalUnlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GlobalUnlockResponse) Reset() {
	*x = GlobalUnlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_lock_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalUnlockResponse) ProtoMessage() {}

func (x *GlobalUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_lock_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalUnlockResponse.ProtoReflect.Descriptor instead.
func (*GlobalUnlockResponse) Descriptor() ([]byte, []int) {
	return file_sync_lock_proto_rawDescGZIP(), []int{7}
}

var File_sync_lock_proto protoreflect.FileDescriptor

var file_sync_lock_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x63,
	0x65, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x22, 0x13, 0x0a, 0x11,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x94, 0x01, 0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x55, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e,
	0x63, 0x65, 0x72, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e,
	0x63, 0x65, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x6f, 0x0a, 0x11, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x71, 0x0a, 0x13, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e,
	0x63, 0x65, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_lock_proto_rawDescOnce sync.Once
	file_sync_lock_proto_rawDescData = file_sync_lock_proto_rawDesc
)

func file_sync_lock_proto_rawDescGZIP() []byte {
	file_sync_lock_proto_rawDescOnce.Do(func() {
		file_sync_lock_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_lock_proto_rawDescData)
	})
	return file_sync_lock_proto_rawDescData
}

var file_sync_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sync_lock_proto_goTypes = []interface{}{
	(*LocalLockRequest)(nil),     // 0: sync.LocalLockRequest
	(*LocalLockResponse)(nil),    // 1: sync.LocalLockResponse
	(*LocalUnlockRequest)(nil),   // 2: sync.LocalUnlockRequest
	(*LocalUnlockResponse)(nil),  // 3: sync.LocalUnlockResponse
	(*GlobalLockRequest)(nil),    // 4: sync.GlobalLockRequest
	(*GlobalLockResponse)(nil),   // 5: sync.GlobalLockResponse
	(*GlobalUnlockRequest)(nil),  // 6: sync.GlobalUnlockRequest
	(*GlobalUnlockResponse)(nil), // 7: sync.GlobalUnlockResponse
}
var file_sync_lock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_lock_proto_init() }
func file_sync_lock_proto_init() {
	if File_sync_lock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sync_lock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalLockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalUnlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lock_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalUnlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lock_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lock_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalLockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lock_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalUnlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_lock_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalUnlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_lock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_lock_proto_goTypes,
		DependencyIndexes: file_sync_lock_proto_depIdxs,
		MessageInfos:      file_sync_lock_proto_msgTypes,
	}.Build()
	File_sync_lock_proto = out.File
	file_sync_lock_proto_rawDesc = nil
	file_sync_lock_proto_goTypes = nil
	file_sync_lock_proto_depIdxs = nil
}
